version: "3.7"
services:
  web1:
    build: ./quote_gen
    container_name: quote-gen-container
    ports:
      - "5000:5000"
    volumes:
      - .:/app   # Mount the current directory to /app in the container
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1   # Enable debug mode for auto-reloading
    command: flask run --host=0.0.0.0

  web2:
    build: ./quote_disp
    container_name: quote-disp-container
    ports:
      - "5001:5001"
    depends_on:
      - web1
